### PR TITLE
Feature/url shortner service implementation v1.0.0

### PR DESCRIPTION
**Pull request by adityarajmishra**
URL Shortener Service

This is a simple URL shortener service built with Java and Spring Boot. It provides REST APIs for shortening URLs, redirecting shortened URLs, and retrieving statistics about the most frequently shortened domains.

### CODE REVIEW

**Comment by anju-infracloud** [comment]
@adityarajmishra The application fails to start as the `mvn clean install` command is failing with below error:
```
[INFO] Scanning for projects...
[INFO] 
[INFO] ----------------------< com.example:urlshortener >----------------------
[INFO] Building urlshortener 0.0.1-SNAPSHOT
[INFO]   from pom.xml
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- clean:3.3.2:clean (default-clean) @ urlshortener ---
[INFO] Deleting /home/hardik/Work/infracloud/urlShortnerService/target
[INFO] 
[INFO] --- resources:3.3.1:resources (default-resources) @ urlshortener ---
[INFO] Copying 1 resource from src/main/resources to target/classes
[INFO] Copying 0 resource from src/main/resources to target/classes
[INFO] 
[INFO] --- compiler:3.13.0:compile (default-compile) @ urlshortener ---
[INFO] Recompiling the module because of changed source code.
[INFO] Compiling 6 source files with javac [debug parameters release 17] to target/classes
[INFO] 
[INFO] --- resources:3.3.1:testResources (default-testResources) @ urlshortener ---
[INFO] skip non existing resourceDirectory /home/hardik/Work/infracloud/urlShortnerService/src/test/resources
[INFO] 
[INFO] --- compiler:3.13.0:testCompile (default-testCompile) @ urlshortener ---
[INFO] Recompiling the module because of changed dependency.
[INFO] Compiling 1 source file with javac [debug parameters release 17] to target/test-classes
[INFO] 
[INFO] --- surefire:3.2.5:test (default-test) @ urlshortener ---
[INFO] Using auto detected provider org.apache.maven.surefire.junitplatform.JUnitPlatformProvider
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running com.example.urlshortener.UrlShortenerServiceTests
OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
18:28:26.943 [main] INFO com.example.urlshortener.service.UrlShortenerService -- Attempting to retrieve original URL for short URL: nonexistent
18:28:26.947 [main] INFO com.example.urlshortener.service.UrlShortenerService -- Short URL not found in cache, checking database
18:28:26.949 [main] ERROR com.example.urlshortener.service.UrlShortenerService -- URL not found for short URL: nonexistent
18:28:26.955 [main] INFO com.example.urlshortener.service.UrlShortenerService -- Attempting to retrieve original URL for short URL: nonexistent
18:28:26.956 [main] INFO com.example.urlshortener.service.UrlShortenerService -- Short URL not found in cache, checking database
18:28:26.956 [main] ERROR com.example.urlshortener.service.UrlShortenerService -- URL not found for short URL: nonexistent
18:28:26.965 [main] INFO com.example.urlshortener.service.UrlShortenerService -- Attempting to retrieve original URL for short URL: abcdefgh
18:28:26.965 [main] INFO com.example.urlshortener.service.UrlShortenerService -- Short URL not found in cache, checking database
[ERROR] Tests run: 7, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.995 s <<< FAILURE! -- in com.example.urlshortener.UrlShortenerServiceTests
[ERROR] com.example.urlshortener.UrlShortenerServiceTests.getTopDomains_ReturnsCorrectOrder -- Time elapsed: 0.015 s <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <example3.com> but was: <example1.com>
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
	at org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:182)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:177)
	at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:1145)
	at com.example.urlshortener.UrlShortenerServiceTests.getTopDomains_ReturnsCorrectOrder(UrlshortenerApplicationTests.java:102)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   UrlShortenerServiceTests.getTopDomains_ReturnsCorrectOrder:102 expected: <example3.com> but was: <example1.com>
[INFO] 
[ERROR] Tests run: 7, Failures: 1, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  4.305 s
[INFO] Finished at: 2024-09-11T18:28:27+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.2.5:test (default-test) on project urlshortener: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/hardik/Work/infracloud/urlShortnerService/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

**Comment by adityarajmishra** [comment]
I checked the Issue and Have Fixed By committing the changes.

**Comment by adityarajmishra** [comment]
rahulmishra@RX297RV65C urlShortnerService %  mvn clean install
[INFO] Scanning for projects...
[INFO]
[INFO] ----------------------< com.example:urlshortener >----------------------
[INFO] Building urlshortener 0.0.1-SNAPSHOT
[INFO]   from pom.xml
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- clean:3.3.2:clean (default-clean) @ urlshortener ---
[INFO] Deleting /Users/rahulmishra/Desktop/Personal Projects/UrlShortnerService/urlShortnerService/target
[INFO]
[INFO] --- resources:3.3.1:resources (default-resources) @ urlshortener ---
[INFO] Copying 1 resource from src/main/resources to target/classes
[INFO] Copying 0 resource from src/main/resources to target/classes
[INFO]
[INFO] --- compiler:3.13.0:compile (default-compile) @ urlshortener ---
[INFO] Recompiling the module because of changed source code.
[INFO] Compiling 6 source files with javac [debug parameters release 17] to target/classes
[INFO] Annotation processing is enabled because one or more processors were found
  on the class path. A future release of javac may disable annotation processing
  unless at least one processor is specified by name (-processor), or a search
  path is specified (--processor-path, --processor-module-path), or annotation
  processing is enabled explicitly (-proc:only, -proc:full).
  Use -Xlint:-options to suppress this message.
  Use -proc:none to disable annotation processing.
[INFO]
[INFO] --- resources:3.3.1:testResources (default-testResources) @ urlshortener ---
[INFO] skip non existing resourceDirectory /Users/rahulmishra/Desktop/Personal Projects/UrlShortnerService/urlShortnerService/src/test/resources
[INFO]
[INFO] --- compiler:3.13.0:testCompile (default-testCompile) @ urlshortener ---
[INFO] Recompiling the module because of changed dependency.
[INFO] Compiling 1 source file with javac [debug parameters release 17] to target/test-classes
[INFO] Annotation processing is enabled because one or more processors were found
  on the class path. A future release of javac may disable annotation processing
  unless at least one processor is specified by name (-processor), or a search
  path is specified (--processor-path, --processor-module-path), or annotation
  processing is enabled explicitly (-proc:only, -proc:full).
  Use -Xlint:-options to suppress this message.
  Use -proc:none to disable annotation processing.
[INFO]
[INFO] --- surefire:3.2.5:test (default-test) @ urlshortener ---
[INFO] Using auto detected provider org.apache.maven.surefire.junitplatform.JUnitPlatformProvider
[INFO]
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running com.example.urlshortener.UrlShortenerServiceTests
WARNING: A Java agent has been loaded dynamically (/Users/rahulmishra/.m2/repository/net/bytebuddy/byte-buddy-agent/1.14.19/byte-buddy-agent-1.14.19.jar)
WARNING: If a serviceability tool is in use, please run with -XX:+EnableDynamicAgentLoading to hide this warning
WARNING: If a serviceability tool is not in use, please run with -Djdk.instrument.traceUsage for more information
WARNING: Dynamic loading of agents will be disallowed by default in a future release
OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
18:47:15.622 [main] INFO com.example.urlshortener.service.UrlShortenerService -- Attempting to retrieve original URL for short URL: nonexistent
18:47:15.626 [main] INFO com.example.urlshortener.service.UrlShortenerService -- Short URL not found in cache, checking database
18:47:15.630 [main] ERROR com.example.urlshortener.service.UrlShortenerService -- URL not found for short URL: nonexistent
18:47:15.646 [main] INFO com.example.urlshortener.service.UrlShortenerService -- Attempting to retrieve original URL for short URL: nonexistent
18:47:15.646 [main] INFO com.example.urlshortener.service.UrlShortenerService -- Short URL not found in cache, checking database
18:47:15.647 [main] ERROR com.example.urlshortener.service.UrlShortenerService -- URL not found for short URL: nonexistent
18:47:15.659 [main] INFO com.example.urlshortener.service.UrlShortenerService -- Attempting to retrieve original URL for short URL: abcdefgh
18:47:15.659 [main] INFO com.example.urlshortener.service.UrlShortenerService -- Short URL not found in cache, checking database
[INFO] Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.522 s -- in com.example.urlshortener.UrlShortenerServiceTests
[INFO]
[INFO] Results:
[INFO]
[INFO] Tests run: 7, Failures: 0, Errors: 0, Skipped: 0
[INFO]
[INFO]
[INFO] --- jar:3.4.2:jar (default-jar) @ urlshortener ---
[INFO] Building jar: /Users/rahulmishra/Desktop/Personal Projects/UrlShortnerService/urlShortnerService/target/urlshortener-0.0.1-SNAPSHOT.jar
[INFO]
[INFO] --- spring-boot:3.3.3:repackage (repackage) @ urlshortener ---
[INFO] Replacing main artifact /Users/rahulmishra/Desktop/Personal Projects/UrlShortnerService/urlShortnerService/target/urlshortener-0.0.1-SNAPSHOT.jar with repackaged archive, adding nested dependencies in BOOT-INF/.
[INFO] The original artifact has been renamed to /Users/rahulmishra/Desktop/Personal Projects/UrlShortnerService/urlShortnerService/target/urlshortener-0.0.1-SNAPSHOT.jar.original
[INFO]
[INFO] --- install:3.1.3:install (default-install) @ urlshortener ---
[INFO] Installing /Users/rahulmishra/Desktop/Personal Projects/UrlShortnerService/urlShortnerService/pom.xml to /Users/rahulmishra/.m2/repository/com/example/urlshortener/0.0.1-SNAPSHOT/urlshortener-0.0.1-SNAPSHOT.pom
[INFO] Installing /Users/rahulmishra/Desktop/Personal Projects/UrlShortnerService/urlShortnerService/target/urlshortener-0.0.1-SNAPSHOT.jar to /Users/rahulmishra/.m2/repository/com/example/urlshortener/0.0.1-SNAPSHOT/urlshortener-0.0.1-SNAPSHOT.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  12.788 s
[INFO] Finished at: 2024-09-11T18:47:17+05:30
[INFO] ------------------------------------------------------------------------
rahulmishra@RX297RV65C urlShortnerService % git add *
The following paths are ignored by one of your .gitignore files:
HELP.md
target
hint: Use -f if you really want to add them.
hint: Turn this message off by running
hint: "git config advice.addIgnoredFile false"
rahulmishra@RX297RV65C urlShortnerService % git commit -m "Issue fix with Test cases"
[feature/urlShortnerService-Implementation-v1.0.0 20f6373] Issue fix with Test cases
 1 file changed, 4 insertions(+), 3 deletions(-)
rahulmishra@RX297RV65C urlShortnerService % git push
Enumerating objects: 19, done.
Counting objects: 100% (19/19), done.
Delta compression using up to 10 threads
Compressing objects: 100% (7/7), done.
Writing objects: 100% (10/10), 726 bytes | 726.00 KiB/s, done.
Total 10 (delta 3), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (3/3), completed with 3 local objects.
To https://github.com/adityarajmishra/urlShortnerService.git
   cfbd909..20f6373  feature/urlShortnerService-Implementation-v1.0.0 -> feature/urlShortnerService-Implementation-v1.0.0
rahulmishra@RX297RV65C urlShortnerService % docker buildx build --tag adityarajmishra/url-shortener .
[+] Building 22.8s (8/8) FINISHED                                                                   docker:desktop-linux
 => [internal] load build definition from Dockerfile                                                                0.0s
 => => transferring dockerfile: 168B                                                                                0.0s
 => [internal] load metadata for docker.io/library/openjdk:17-jdk-slim                                             22.3s
 => [auth] library/openjdk:pull token for registry-1.docker.io                                                      0.0s
 => [internal] load .dockerignore                                                                                   0.0s
 => => transferring context: 2B                                                                                     0.0s
 => [internal] load build context                                                                                   0.3s
 => => transferring context: 47.48MB                                                                                0.3s
 => CACHED [1/2] FROM docker.io/library/openjdk:17-jdk-slim@sha256:aaa3b3cb27e3e520b8f116863d0580c438ed55ecfa0bc12  0.0s
 => [2/2] COPY target/urlshortener-0.0.1-SNAPSHOT.jar app.jar                                                       0.1s
 => exporting to image                                                                                              0.1s
 => => exporting layers                                                                                             0.1s
 => => writing image sha256:06656389b78647378a0423184c7d925d1c7f97350c1bf1268dffc22db5ebbe89                        0.0s
 => => naming to docker.io/adityarajmishra/url-shortener                                                            0.0s

What's next:
    View a summary of image vulnerabilities and recommendations → docker scout quickview
rahulmishra@RX297RV65C urlShortnerService % docker push adityarajmishra/url-shortener
Using default tag: latest
The push refers to repository [docker.io/adityarajmishra/url-shortener]
5daa03494a37: Pushed
c82e5bf37b8a: Layer already exists
2f263e87cb11: Layer already exists
f941f90e71a8: Layer already exists
latest: digest: sha256:76d57dc1b7d552aa50a53d80156b1576d129c6dc091233935b4a28eb402609dd size: 1165
rahulmishra@RX297RV65C urlShortnerService %


@anju-infracloud  : Also Pushed to docker Image as well

**Comment by anju-infracloud** [comment]
@adityarajmishra I have tried running the shorten endpoint for multipl URLs and have been facing below issues:

1. All the URLs are getting the same shorten ID. I have tried below curl commands and all returned `aHR0cHM6` as shortened ID.

```
curl --location 'http://localhost:8080/api/shorten' --header 'Content-Type: application/json' --data 'https://youtube.com'
aHR0cHM6

curl --location 'http://localhost:8080/api/shorten' --header 'Content-Type: application/json' --data 'https://google.com'
aHR0cHM6

curl --location 'http://localhost:8080/api/shorten' --header 'Content-Type: application/json' --data 'https://example.com'
aHR0cHM6
```

2. The example which you have provided in the README file for the shorten endpoint generates a different shortened ID but when I try to redirect endpoint with it, it takes me to below error page:
image

3. The metrics endpoint is returning all the domain incorrectly as below:
image

**Comment by adityarajmishra** [comment]
Looking into this @anju-infracloud

**Comment by adityarajmishra** [comment]
TEST CASES PASSED :

rahulmishra@RX297RV65C urlShortnerService %  mvn clean install
[INFO] Scanning for projects...
[INFO]
[INFO] ----------------------< com.example:urlshortener >----------------------
[INFO] Building urlshortener 0.0.1-SNAPSHOT
[INFO]   from pom.xml
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- clean:3.3.2:clean (default-clean) @ urlshortener ---
[INFO] Deleting /Users/rahulmishra/Desktop/Personal Projects/UrlShortnerService/urlShortnerService/target
[INFO]
[INFO] --- resources:3.3.1:resources (default-resources) @ urlshortener ---
[INFO] Copying 1 resource from src/main/resources to target/classes
[INFO] Copying 0 resource from src/main/resources to target/classes
[INFO]
[INFO] --- compiler:3.13.0:compile (default-compile) @ urlshortener ---
[INFO] Recompiling the module because of changed source code.
[INFO] Compiling 6 source files with javac [debug parameters release 17] to target/classes
[INFO] Annotation processing is enabled because one or more processors were found
  on the class path. A future release of javac may disable annotation processing
  unless at least one processor is specified by name (-processor), or a search
  path is specified (--processor-path, --processor-module-path), or annotation
  processing is enabled explicitly (-proc:only, -proc:full).
  Use -Xlint:-options to suppress this message.
  Use -proc:none to disable annotation processing.
[INFO]
[INFO] --- resources:3.3.1:testResources (default-testResources) @ urlshortener ---
[INFO] skip non existing resourceDirectory /Users/rahulmishra/Desktop/Personal Projects/UrlShortnerService/urlShortnerService/src/test/resources
[INFO]
[INFO] --- compiler:3.13.0:testCompile (default-testCompile) @ urlshortener ---
[INFO] Recompiling the module because of changed dependency.
[INFO] Compiling 1 source file with javac [debug parameters release 17] to target/test-classes
[INFO] Annotation processing is enabled because one or more processors were found
  on the class path. A future release of javac may disable annotation processing
  unless at least one processor is specified by name (-processor), or a search
  path is specified (--processor-path, --processor-module-path), or annotation
  processing is enabled explicitly (-proc:only, -proc:full).
  Use -Xlint:-options to suppress this message.
  Use -proc:none to disable annotation processing.
[INFO]
[INFO] --- surefire:3.2.5:test (default-test) @ urlshortener ---
[INFO] Using auto detected provider org.apache.maven.surefire.junitplatform.JUnitPlatformProvider
[INFO]
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running com.example.urlshortener.UrlShortenerServiceTests
WARNING: A Java agent has been loaded dynamically (/Users/rahulmishra/.m2/repository/net/bytebuddy/byte-buddy-agent/1.14.19/byte-buddy-agent-1.14.19.jar)
WARNING: If a serviceability tool is in use, please run with -XX:+EnableDynamicAgentLoading to hide this warning
WARNING: If a serviceability tool is not in use, please run with -Djdk.instrument.traceUsage for more information
WARNING: Dynamic loading of agents will be disallowed by default in a future release
OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
09:09:36.889 [main] INFO com.example.urlshortener.service.UrlShortenerService -- Attempting to retrieve original URL for short URL: nonexistent
09:09:36.895 [main] INFO com.example.urlshortener.service.UrlShortenerService -- Short URL not found in cache, checking database
09:09:36.898 [main] ERROR com.example.urlshortener.service.UrlShortenerService -- URL not found for short URL: nonexistent
09:09:36.913 [main] INFO com.example.urlshortener.service.UrlShortenerService -- Attempting to retrieve original URL for short URL: nonexistent
09:09:36.914 [main] INFO com.example.urlshortener.service.UrlShortenerService -- Short URL not found in cache, checking database
09:09:36.914 [main] ERROR com.example.urlshortener.service.UrlShortenerService -- URL not found for short URL: nonexistent
09:09:36.927 [main] INFO com.example.urlshortener.service.UrlShortenerService -- Attempting to retrieve original URL for short URL: abcdefgh
09:09:36.927 [main] INFO com.example.urlshortener.service.UrlShortenerService -- Short URL not found in cache, checking database
[INFO] Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.777 s -- in com.example.urlshortener.UrlShortenerServiceTests
[INFO]
[INFO] Results:
[INFO]
[INFO] Tests run: 7, Failures: 0, Errors: 0, Skipped: 0
[INFO]
[INFO]
[INFO] --- jar:3.4.2:jar (default-jar) @ urlshortener ---
[INFO] Building jar: /Users/rahulmishra/Desktop/Personal Projects/UrlShortnerService/urlShortnerService/target/urlshortener-0.0.1-SNAPSHOT.jar
[INFO]
[INFO] --- spring-boot:3.3.3:repackage (repackage) @ urlshortener ---
[INFO] Replacing main artifact /Users/rahulmishra/Desktop/Personal Projects/UrlShortnerService/urlShortnerService/target/urlshortener-0.0.1-SNAPSHOT.jar with repackaged archive, adding nested dependencies in BOOT-INF/.
[INFO] The original artifact has been renamed to /Users/rahulmishra/Desktop/Personal Projects/UrlShortnerService/urlShortnerService/target/urlshortener-0.0.1-SNAPSHOT.jar.original
[INFO]
[INFO] --- install:3.1.3:install (default-install) @ urlshortener ---
[INFO] Installing /Users/rahulmishra/Desktop/Personal Projects/UrlShortnerService/urlShortnerService/pom.xml to /Users/rahulmishra/.m2/repository/com/example/urlshortener/0.0.1-SNAPSHOT/urlshortener-0.0.1-SNAPSHOT.pom
[INFO] Installing /Users/rahulmishra/Desktop/Personal Projects/UrlShortnerService/urlShortnerService/target/urlshortener-0.0.1-SNAPSHOT.jar to /Users/rahulmishra/.m2/repository/com/example/urlshortener/0.0.1-SNAPSHOT/urlshortener-0.0.1-SNAPSHOT.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  13.986 s
[INFO] Finished at: 2024-09-18T09:09:39+05:30
[INFO] ------------------------------------------------------------------------







CURL FOR ALL THE END POINTS :


curl --location 'http://localhost:8080/api/shorten' \
--header 'Content-Type: application/json' \
--data '"https://www.youtube.com/"'

GztArgTc



curl --location 'http://localhost:8080/api/shorten' \
--header 'Content-Type: application/json' \
--data '"https://google.com"'

43lJprez



curl --location 'http://localhost:8080/api/shorten' \
--header 'Content-Type: application/json' \
--data '"https://example.com"'

m3mlsr4w




curl --location 'http://localhost:8080/api/metrics/top-domains'


[
    {
        "youtube.com": 3
    },
    {
        "google.com": 2
    },
    {
        "example.com": 1
    }
]




DOCKER BUILD UPDATE WITH THE CHANGES:

rahulmishra@RX297RV65C urlShortnerService % docker buildx build --tag adityarajmishra/url-shortener .
[+] Building 2.9s (8/8) FINISHED                                                                    docker:desktop-linux
 => [internal] load build definition from Dockerfile                                                                0.0s
 => => transferring dockerfile: 168B                                                                                0.0s
 => [internal] load metadata for docker.io/library/openjdk:17-jdk-slim                                              2.3s
 => [auth] library/openjdk:pull token for registry-1.docker.io                                                      0.0s
 => [internal] load .dockerignore                                                                                   0.0s
 => => transferring context: 2B                                                                                     0.0s
 => [internal] load build context                                                                                   0.3s
 => => transferring context: 47.48MB                                                                                0.3s
 => CACHED [1/2] FROM docker.io/library/openjdk:17-jdk-slim@sha256:aaa3b3cb27e3e520b8f116863d0580c438ed55ecfa0bc12  0.0s
 => [2/2] COPY target/urlshortener-0.0.1-SNAPSHOT.jar app.jar                                                       0.1s
 => exporting to image                                                                                              0.1s
 => => exporting layers                                                                                             0.1s
 => => writing image sha256:9f4f014672827efafdefe83f7cda90697d756d4ae92ade87a9040233aa0ad749                        0.0s
 => => naming to docker.io/adityarajmishra/url-shortener                                                            0.0s

What's next:
    View a summary of image vulnerabilities and recommendations → docker scout quickview
rahulmishra@RX297RV65C urlShortnerService % docker push adityarajmishra/url-shortener
Using default tag: latest
The push refers to a repository [docker.io/adityarajmishra/url-shortener]
9f2aba4a05d4: Pushed
c82e5bf37b8a: Layer already exists
2f263e87cb11: Layer already exists
f941f90e71a8: Layer already exists
latest: digest: sha256:03648bf2939be5e14d1defedc13b4514e619418e7e03ee48039edf01c3880c61 size: 1165
rahulmishra@RX297RV65C urlShortnerService %


@anju-infracloud: FOR THE REDIRECTION please check the README.md as I have instructed that we need to turn off the settings in post ma for automatic redirection and then hit the API it will give you 302 found which confirms the redirection.

**Comment by adityarajmishra** [comment]
@anju-infracloud: All the issues are fixed and pushed to the docker image.

**Pull request merged**
